name = "gameclub"
# 修改main入口点指向Next.js构建输出的文件
main = ".next/standalone/server.js"
compatibility_date = "2023-10-19"

# 禁用遥测数据收集
send_metrics = false

[site]
bucket = ".next"

[build]
command = "npm run build"
output_dir = ".next"

# 添加环境变量定义，避免运行时赋值
[define]
"process.env.NODE_ENV" = "\"production\""

[env.production]
workers_dev = true