name = "gamdaclub"
# 修改main入口点指向Next.js构建输出的文件
main = ".next/standalone/server.js"
compatibility_date = "2024-09-23"
# 添加nodejs兼容性标志
compatibility_flags = ["nodejs_compat"]

# 禁用遥测数据收集
send_metrics = false

[site]
bucket = ".next"

[build]
command = "npm run build"

# 添加环境变量定义，避免运行时赋值
[define]
"process.env.NODE_ENV" = "\"production\""

[env.production]
workers_dev = true